### ISSUE TITLE
Unable to generate ". Pkl" file

### ISSUE THREAD

**Issue by ZhouBay-TF** [spoliveira/HERclassHE#1]
Thank you very much for your work. It's great. I want to run your program. I need the ". Pkl" file when testing, but I can't understand Hashi_ "Dir_thumbnails" in segmentation.py, so ". Pkl" cannot be generated

**Comment by TiagoFilipeSousaGoncalves** [comment]
@spoliveira can you help?

**Comment by TiagoFilipeSousaGoncalves** [comment]
> Thank you very much for your work. It's great. I want to run your program. I need the ". Pkl" file when testing, but I can't understand Hashi_ "Dir_thumbnails" in segmentation.py, so ". Pkl" cannot be generated

@xinkangzhou you may also send an e-mail to: sara.i.oliveira@inesctec.pt ;)

Sorry for the delayed answer!

**Comment by Panchojr7** [comment]
@xinkangzhou How did you solve it? because I am also asked to have the .png images before generating them.

**Comment by spoliveira** [comment]
Hi @xinkangzhou and @Panchojr7 

Sorry for the late reply.
The "dir_thumbnails" in the "HASHI_segmentation.py" file is where you define the main folder where you want the HASHI masks (.png) to be stored. The binary masks will be stored in a subfolder called "HASHI_msk". 
Then, to generate the .pkl files, you have to set "dir_masks" = "HASHI_msk" folder path, in the "wsi_main.py".
